CREATE DATABASE IF NOT EXISTS mydb;

USE mydb; -- SELECT DATABASE

DROP TABLE IF EXISTS mytable;
CREATE TABLE IF NOT EXISTS mytable(
    col1 VARCHAR(255),
    col2 VARCHAR(255)
);

INSERT INTO mytable (col1,col2)
VALUES ('hi','hi');

