CREATE DATABASE IF NOT EXISTS mydb;

USE mydb; -- SELECT DATABASE

DROP TABLE IF EXISTS mytable;
CREATE TABLE IF NOT EXISTS mytable(
    col1 VARCHAR(255),
    col2 VARCHAR(255)
);

INSERT INTO mytable (col1,col2)
VALUES ('hi','hi');

DROP TABLE IF EXISTS patients_age;
CREATE TABLE IF NOT EXISTS patients_age(
    SUBJECT_ID INT,
    DOB VARCHAR(255),
    PRIMARY KEY (SUBJECT_ID)
);

LOAD DATA INFILE '/volume/data/patients_age.csv'
INTO TABLE patients_age
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

DROP TABLE IF EXISTS predictions;
CREATE TABLE IF NOT EXISTS predictions(
    PREDICTION_ID INT NOT NULL AUTO_INCREMENT,
    SUBJECT_ID INT,
    PRED_TIME TIMESTAMP,
    RISK_SCORE FLOAT
);